import streamlit as st
import pandas as pd
import numpy as np
import xgboost as xgb


parking_col = st.selectbox(label='Select PARKING:',options=["BOTH","TWO_WHEELER","FOUR_WHEELER","NONE"])

balconies_col = st.selectbox(label='Select balconies:',options=["0","1","2","3","4","4+"])

furnsihing_col = st.selectbox(label='Select furnishingDesc:',options=["UN FURNISHED","SEMI FURNISHED","FULL FURNISHED"])

bhk_col = st.selectbox(label='Select type_bhk:',options=["1RK","1BHK","2BHK","3BHK","4BHK","4+BHK"])

bath_col = st.selectbox(label='Select bathroom:',options=["1","2","3","4","5","5+"])

swimming_col = st.selectbox(label='Select swimmingPool:',options=["NO","YES"])

lift_col = st.selectbox(label='Select lift:',options=["YES","NO"])

gym_col = st.selectbox(label='Select gym:',options=["YES","NO"])

isMaintenance_col = st.selectbox(label='Select isMaintenance:',options=["YES","YES"])

totalFloor_col = st.selectbox(label='Select totalfloors:',options=["0","1-5","6-14","14+"])

floor_col = st.selectbox(label='Select Floor:',options=["0","1-7","8-19","19+"])

maintenance_col = st.selectbox(label='Select maintenanceAmt:',options=["0","0-500","500-1000","1000-1500","1500-2000","2000-3000","3000+"])

locality_col = st.selectbox(label='Select locality:',options=["WHITEFIELDS",
                                                            "NANAKRAMGUDA",
                                                            "KOKAPET",
                                                            "NANAKARAMGUDA",
                                                            "GOPANAPALLI",
                                                            "NANAKRAM GUDA",
                                                            "PUPPALGUDA", 
                                                            "NARSINGI", 
                                                            "KOTHAGUDA", 
                                                            "NALLAGANDLA",
                                                            "KHAJAGUDA", 
                                                            "GOPANPALLY",
                                                            "NEKNAMPUR",
                                                            "GACHIBOWLI", 
                                                            "PEERANCHURUVU", 
                                                            "NALAGANDLA",
                                                            "KONDAPUR",  
                                                            "BANJARA HILLS", 
                                                            "MADINAGUDA", 
                                                            "MANIKONDA",
                                                            "PUNJAGUTTA",
                                                            "HITEC CITY", 
                                                            "SOMAJIGUDA", 
                                                            "HITECH CITY",
                                                            "TELLAPUR", 
                                                            "MADHAPUR", 
                                                            "LAKDIKAPUL", 
                                                            "PUPPALAGUDA",
                                                            "RAMGOPALPET", 
                                                            "HAKIMPET", 
                                                            "MASAB TANK", 
                                                            "JUBILEE HILLS",
                                                            "UPPARPALLY", 
                                                            "UPPERPALLY", 
                                                            "MADHURA NAGAR", 
                                                            "ADIBATLA", 
                                                            "AMEERPET", 
                                                            "YAPRAL", 
                                                            "SERILINGAMPALLY", 
                                                            'HYDER NAGAR',
                                                            "WEST MARREDPALLY", 
                                                            "KONDAPUR", 
                                                            "KARKHANA", 
                                                            "HABSIGUDA",
                                                            "TOLI CHOWKI", 
                                                            "HIMAYATNAGAR", 
                                                            "EAST MARREDPALLY", 
                                                            "KHAIRTABAD", 
                                                            "MANIKONDA JAGIR",
                                                            "CHIKKADPALLY", 
                                                            "FILM NAGAR", 
                                                            'HI-TECH CITY', 
                                                            "HAFEEZPET", 
                                                            "MEHDIPATNAM",
                                                            "SHAIKPET", 
                                                            "KAVADIGUDA",
                                                            "PRAGATI NAGAR", 
                                                            "NARAYANGUDA", 
                                                            "POCHARAM",
                                                            "KOMPALLY",
                                                            "HYDERABAD", 
                                                            "MIYAPUR", 
                                                            "NALLAKUNTA", 
                                                            "MADEENAGUDA", 
                                                            "QUTUB SHAHI TOMBS", 
                                                            "BOWRAMPET", 
                                                            "SAINIKPURI", 
                                                            "SERILINGAMPALLE",
                                                            "MALAKPET", 
                                                            "KUKATPALLY",
                                                            "TARNAKA", 
                                                            "BEGUMPET",
                                                            "SANJEEVA REDDY NAGAR",
                                                            "HYDERSHAKOTE", 
                                                            "NIZAMPET", 
                                                            "SECUNDERABAD",
                                                            "YELLA REDDY GUDA", 
                                                            "BALKAMPET", 
                                                            "CHANDA NAGAR", 
                                                            "LINGAMPALLY", 
                                                            "other", 
                                                            "KUKATPALLY", 
                                                            "ATTAPUR",
                                                            "HYDERGUDA", 
                                                            "PRAGATHI NAGAR", 
                                                            "BANDLAGUDA",
                                                            "BOWENPALLY", 
                                                            "ANNOJIGUDA", 
                                                            "SERLINGAMPALLI", 
                                                            "ZAMISTANPUR", 
                                                            "OLD MALAKPET", 
                                                            "BACHUPALLY", 
                                                            "NACHARAM",
                                                            "PADMARAO NAGAR", 
                                                            "BHOIGUDA",
                                                            "BANDLAGUDA JAGIR",
                                                            "METTUGUDA",
                                                            "AMBERPET",
                                                            "MOOSAPET", 
                                                            "NEW NALLAKUNTA", 
                                                            "OSMAN NAGAR", 
                                                            "MANSOORABAD", 
                                                            "MALLAPUR", 
                                                            "SHAMSHABAD",
                                                            "RAIDURG KHALSA", 
                                                            "ADIKMET", 
                                                            "BANDAM KOMMU",
                                                            "KACHIGUDA", 
                                                            "CHANDANAGAR", 
                                                            "IBRAHIM BAGH", 
                                                            "MUSHEERABAD", 
                                                            "TRIMULGHERRY", 
                                                            "OLD BOWENPALLY", 
                                                            "BORABANDA",
                                                            "NAGOLE", 
                                                            "A S RAO NAGAR", 
                                                            "GUDIMALKAPUR", 
                                                            "SANATH NAGAR", 
                                                            "DILSUKHNAGAR",
                                                            "KHAIRATABAD",
                                                            "MALLAMPET", 
                                                            "BHARAT HEAVY ELECTRICALS LIMITED",
                                                            "SHIVAJI NAGAR",
                                                            "YOUSUFGUDA",
                                                            "JEEDIMETLA", 
                                                            "ERRAGADDA",
                                                            "KOTHAPET",
                                                            "UPPAL", 
                                                            "KAPRA",
                                                            "AMEENPUR", 
                                                            "BOLARUM",
                                                            "ALWAL",
                                                            "A. S. RAO NAGAR", 
                                                            "MAHADEVPUR COLONY", 
                                                            "LB NAGAR", 
                                                            "KRISHNA REDDY PET",
                                                            "SAIDABAD",
                                                            "SAROORNAGAR",
                                                            "MALKAJGIRI",
                                                            "MEDIPALLY",
                                                            "BEERAMGUDA",
                                                            "HASTINAPURAM",
                                                            "JAWAHAR NAGAR", 
                                                            "PATANCHERU", 
                                                            "GANDAMGUDA", 
                                                            "BAHADURGUDA",
                                                            "LANGAR HOUZ", 
                                                            "VANASTHALIPURAM", 
                                                            "RAMACHANDRA PURAM",
                                                            "RAMACHANDRAPURAM", 
                                                            "RAMANTHAPUR", 
                                                            "CHAMPAPET",
                                                            "RAM NAGAR",
                                                            "BALANAGAR",
                                                            "KISMATPUR",
                                                            "PEERZADIGUDA",
                                                            "KAMALAPRASAD NAGAR",
                                                            "OLD ALWAL",
                                                            "SAFILGUDA",
                                                            "KARMANGHAT",
                                                            "KHARMANGHAT",
                                                            "HAYATHNAGAR",
                                                            "QUTHBULLAPUR",
                                                            "DAMMAIGUDA",
                                                            "L. B. NAGAR",
                                                            "MOULA ALI",
                                                            "KISTAREDDYPET", 
                                                            "BODUPPAL",
                                                            "RAMPALLY", 
                                                            "BALAPUR",
                                                            "KUSHAIGUDA", 
                                                            "RODAMESTRI NAGAR",
                                                            "B N REDDY NAGAR", 
                                                            "JAGATHGIRI GUTTA",
                                                            "GURRAM GUDA", 
                                                            "RAMACHANDRAPURAM", 
                                                            "NEREDMET", 
                                                            "MEERPET", 
                                                            "BADANGPET", 
                                                            "JILLALGUDA", 
                                                            "SURARAM", 
                                                            "JILLELAGUDA", 
                                                            "ALMASGUDA", 
                                                            "PEDDA AMBERPET",  
                                                            "NAGARAM", 
                                                            "BOLLARAM",
                                                              ])


##################33

balconies_dict={'4+': 6, '4': 5, '3': 4, '2': 3, '1': 2, '0': 1}
bath_dict={'5+': 6, '5': 5, '4': 4, '3': 3, '2': 2, '1': 1}
furnsihing_dict= {"FULL FURNISHED": 3, 'SEMI FURNISHED': 2, 'UN FURNISHED': 1}
parking_dict= {'FOUR_WHEELER': 4, 'BOTH': 3, 'TWO_WHEELER': 2, 'NONE': 1}
bhk_dict={'4+BHK': 6, '4BHK': 5, '3BHK': 4, '2BHK': 3, '1BHK': 2, '1RK': 1}
bath_dict= {'0': 3, '1-5': 2, '5+': 1},
maintenance_col= {"0":,"0-500":,"500-1000","1000-1500","1500-2000","2000-3000","3000+"},
 {'14+': 4, '6-14': 3, '1-5': 2, '0': 1},
 {'19+': 4, '8-19': 3, '1-7': 2, '0': 1},
 {'KOKAPET': 96,
  'NANAKARAMGUDA': 95,
  'PUPPALGUDA': 94,
  'NARSINGI': 93,
  'KOTHAGUDA': 92,
  'NALLAGANDLA': 91,
  'GACHIBOWLI': 90,
  'KONDAPUR': 89,
  'BANJARA HILLS': 88,
  'MADINAGUDA': 87,
  'MANIKONDA': 86,
  'HITEC CITY': 85,
  'SOMAJIGUDA': 84,
  'TELLAPUR': 83,
  'MADHAPUR': 82,
  'PUPPALAGUDA': 81,
  'JUBILEE HILLS': 80,
  'UPPARPALLY': 79,
  'AMEERPET': 78,
  'SERILINGAMPALLY': 77,
  'WEST MARREDPALLY': 76,
  'HABSIGUDA': 75,
  'TOLI CHOWKI': 74,
  'HIMAYATNAGAR': 73,
  'MANIKONDA JAGIR': 72,
  'HAFEEZPET': 71,
  'MEHDIPATNAM': 70,
  'SHAIKPET': 69,
  'KAVADIGUDA': 68,
  'POCHARAM': 67,
  'KOMPALLY': 66,
  'MIYAPUR': 65,
  'MADEENAGUDA': 64,
  'SAINIKPURI': 63,
  'SERILINGAMPALLE': 62,
  'MALAKPET': 61,
  'KUKATPALLY': 60,
  'TARNAKA': 59,
  'BEGUMPET': 58,
  'SANJEEVA REDDY NAGAR': 57,
  'NIZAMPET': 56,
  'SECUNDERABAD': 55,
  'BALKAMPET': 54,
  'CHANDA NAGAR': 53,
  'other': 52,
  'ATTAPUR': 51,
  'PRAGATHI NAGAR': 50,
  'BOWENPALLY': 49,
  'SERLINGAMPALLI': 48,
  'BACHUPALLY': 47,
  'NACHARAM': 46,
  'PADMARAO NAGAR': 45,
  'BANDLAGUDA JAGIR': 44,
  'AMBERPET': 43,
  'MOOSAPET': 42,
  'NEW NALLAKUNTA': 41,
  'OSMAN NAGAR': 40,
  'ADIKMET': 39,
  'OLD BOWENPALLY': 38,
  'BORABANDA': 37,
  'NAGOLE': 36,
  'SANATH NAGAR': 35,
  'DILSUKHNAGAR': 34,
  'BHARAT HEAVY ELECTRICALS LIMITED': 33,
  'GAJULARAMARAM': 32,
  'MOTI NAGAR': 31,
  'YOUSUFGUDA': 30,
  'JEEDIMETLA': 29,
  'ERRAGADDA': 28,
  'KOTHAPET': 27,
  'UPPAL': 26,
  'KAPRA': 25,
  'AMEENPUR': 24,
  'BOLARUM': 23,
  'ALWAL': 22,
  'A. S. RAO NAGAR': 21,
  'LB NAGAR': 20,
  'SAROORNAGAR': 19,
  'MALKAJGIRI': 18,
  'BEERAMGUDA': 17,
  'HASTINAPURAM': 16,
  'LANGAR HOUZ': 15,
  'VANASTHALIPURAM': 14,
  'RAMACHANDRA PURAM': 13,
  'RAMACHANDRAPURAM': 12,
  'RAMANTHAPUR': 11,
  'PEERZADIGUDA': 10,
  'HAYATHNAGAR': 9,
  'QUTHBULLAPUR': 8,
  'MOULA ALI': 7,
  'BODUPPAL': 6,
  'JAGATHGIRI GUTTA': 5,
  'NEREDMET': 4,
  'MEERPET': 3,
  'BADANGPET': 2,
  'NAGARAM': 1}